model:
  name: "mobilenetv4"
  pretrained: False
  num_classes: 3
  drop_path_rate: 0.1

training:
  batch_size: 256
  epochs: 40
  optimizer:
    type: "adamw"
    lr: 1e-4
    weight_decay: 0.05
  use_cuda_amp: True

  lr_scheduler:
    type: "cosine"
    warmup_epochs: 5

data:
  dataset_path: "./datasets/skill_icons"
  input_size: 64
  split_ratio: 0.9  # 可配置的拆分比例
  onnx_path: "checkpoints/mobilenetv4.onnx"
