model:
  name: shufflenetv2
  pretrained: true
  num_classes: 3
  drop_path_rate: 0.2

training:
  epochs: 50
  batch_size: 64
  optimizer:
    lr: 0.001
    weight_decay: 0.0001

data:
  dataset_path: datasets/skill_icons
  input_size: 64
  split_ratio: 0.9